apiVersion: cloud.grafana.crossplane.io/v1alpha1
kind: Stack
metadata:
  name: my-stack
spec:
  forProvider:
    slug: 'crossplanetest'
    name: 'crossplanetest'
    regionSlug: "us"
  providerConfigRef:
    name: grafana-cloud-provider