apiVersion: enterprise.grafana.crossplane.io/v1alpha1
kind: Report
metadata:
  name: cloud-stack-report
spec:
  forProvider:
    name: my-report
    message: Test Report!
    dashboardRef:
      name: cloud-stack-dashboard
    recipients: 
      - julien.duchesne@grafana.com
    schedule:
      - frequency: never
  providerConfigRef:
    name: grafana-cloud-instance-provider